spring.application.name=drumigo

# Fill these values in application-dev.properties (gitignored) for local dev.
mapbox.api.key=
app.frontend.url=

spring.mail.host=
spring.mail.port=
spring.mail.username=
spring.mail.password=
spring.mail.properties.mail.smtp.auth=
spring.mail.properties.mail.debug=

spring.profiles.active=dev
