spring.application.name=drumigo
mapbox.api.key=${MAPBOX_API_KEY}

app.frontend.url=${FRONTEND_URL}

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${SPRING_EMAIL}
spring.mail.password=${SPRING_EMAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.debug=true

jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION}