-- H2 Test Data for Profile Page Testing
-- Run this script in H2 Console to create test users with different roles
-- This script is idempotent and can be run multiple times safely
--
-- IMPORTANT: You MUST start the Spring Boot application FIRST!
-- The application creates the database schema automatically via Hibernate.
-- This script only inserts data into existing tables.
--
-- Steps:
--   1. Start the Spring Boot application: ./mvnw spring-boot:run (or run from IDE)
--   2. Wait for the application to fully start
--   3. Open H2 Console: http://localhost:8080/h2-console
--   4. Connect with:
--        JDBC URL: jdbc:h2:mem:drumigo;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
--        User: sa
--        Password: (empty)
--   5. Paste this script and click "Run"
--
-- If you get errors like "Table ... not found (this database is empty)":
-- - You are connected to an empty in-memory database (wrong URL / wrong app instance / app not started).
-- - To make this script usable even in an empty H2 database, it includes CREATE TABLE IF NOT EXISTS
--   for the minimal set of tables needed by the profile page.

-- ---------------------------------------------------------------------------
-- Minimal schema (only used if tables don't exist)
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS vehicle_types (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(255) NOT NULL UNIQUE,
  start_price DECIMAL(10, 2) NOT NULL,
  price_per_km DECIMAL(10, 2) NOT NULL
);

CREATE TABLE IF NOT EXISTS users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  dtype VARCHAR(31),
  name VARCHAR(255) NOT NULL,
  surname VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL UNIQUE,
  password_hash VARCHAR(255),
  address VARCHAR(255),
  phone VARCHAR(255),
  profile_picture_url TEXT,
  blocked BOOLEAN NOT NULL DEFAULT FALSE,
  role VARCHAR(50) NOT NULL,
  created_at TIMESTAMP NOT NULL,
  updated_at TIMESTAMP
);

CREATE TABLE IF NOT EXISTS passengers (
  user_id BIGINT PRIMARY KEY,
  CONSTRAINT fk_passengers_user FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS drivers (
  user_id BIGINT PRIMARY KEY,
  active_driver BOOLEAN NOT NULL DEFAULT FALSE,
  last_state_change_at TIMESTAMP,
  CONSTRAINT fk_drivers_user FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS admins (
  user_id BIGINT PRIMARY KEY,
  CONSTRAINT fk_admins_user FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS vehicles (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  driver_id BIGINT NOT NULL UNIQUE,
  license_plate VARCHAR(20) NOT NULL UNIQUE,
  vehicle_type_id BIGINT NOT NULL,
  num_seats INT NOT NULL,
  baby_friendly BOOLEAN NOT NULL DEFAULT FALSE,
  pet_friendly BOOLEAN NOT NULL DEFAULT FALSE,
  current_lat DECIMAL(10, 8),
  current_lng DECIMAL(11, 8),
  CONSTRAINT fk_vehicles_driver FOREIGN KEY (driver_id) REFERENCES drivers(user_id),
  CONSTRAINT fk_vehicles_vehicle_type FOREIGN KEY (vehicle_type_id) REFERENCES vehicle_types(id)
);

-- Insert Vehicle Types first (required for vehicles)
-- Using MERGE to make it idempotent (inserts if not exists, updates if exists)
MERGE INTO vehicle_types (name, price_per_km, start_price) KEY (name) VALUES
('STANDARD', 1.50, 2.00),
('LUXURY', 2.50, 5.00),
('VAN', 2.00, 3.50);

-- Insert Passenger User (Password: Password123)
MERGE INTO users (dtype, name, surname, email, password_hash, address, phone, profile_picture_url, blocked, role, created_at, updated_at) KEY (email) VALUES
('Passenger', 'Ana', 'Petrović', 'ana.petrovic@example.com', '008c70392e3abfbd0fa47bbc2ed96aa99bd49e159727fcba0f2e6abeb3a9d601', 'Bulevar Oslobođenja 10, Novi Sad', '+381641234567', null, false, 'PASSENGER', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());

MERGE INTO passengers (user_id) KEY (user_id) VALUES ((SELECT id FROM users WHERE email = 'ana.petrovic@example.com'));

-- Insert Driver User (with vehicle) (Password: Password123)
MERGE INTO users (dtype, name, surname, email, password_hash, address, phone, profile_picture_url, blocked, role, created_at, updated_at) KEY (email) VALUES
('Driver', 'Marko', 'Jovanović', 'marko.jovanovic@example.com', '008c70392e3abfbd0fa47bbc2ed96aa99bd49e159727fcba0f2e6abeb3a9d601', 'Narodnih Heroja 25, Beograd', '+381652345678', null, false, 'DRIVER', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());

MERGE INTO drivers (user_id, active_driver, last_state_change_at) KEY (user_id) VALUES
((SELECT id FROM users WHERE email = 'marko.jovanovic@example.com'), true, CURRENT_TIMESTAMP());

-- Insert Vehicle for Driver (license_plate is required)
MERGE INTO vehicles (driver_id, license_plate, vehicle_type_id, num_seats, baby_friendly, pet_friendly, current_lat, current_lng) KEY (license_plate) VALUES
(
  (SELECT id FROM users WHERE email = 'marko.jovanovic@example.com'),
  'NS-001-AB',
  (SELECT id FROM vehicle_types WHERE name = 'STANDARD'),
  4,
  true,
  false,
  45.2671,
  19.8335
);

-- Insert Admin User (Password: Password123)
MERGE INTO users (dtype, name, surname, email, password_hash, address, phone, profile_picture_url, blocked, role, created_at, updated_at) KEY (email) VALUES
('Admin', 'Stefan', 'Nikolić', 'stefan.nikolic@drumigo.com', '008c70392e3abfbd0fa47bbc2ed96aa99bd49e159727fcba0f2e6abeb3a9d601', 'Trg Republike 1, Beograd', '+381663456789', null, false, 'ADMIN', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());

MERGE INTO admins (user_id) KEY (user_id) VALUES ((SELECT id FROM users WHERE email = 'stefan.nikolic@drumigo.com'));

-- Insert another Driver with different vehicle type (Luxury) (Password: Password123)
MERGE INTO users (dtype, name, surname, email, password_hash, address, phone, profile_picture_url, blocked, role, created_at, updated_at) KEY (email) VALUES
('Driver', 'Jelena', 'Milošević', 'jelena.milosevic@example.com', '008c70392e3abfbd0fa47bbc2ed96aa99bd49e159727fcba0f2e6abeb3a9d601', 'Knez Mihailova 30, Beograd', '+381641112222', null, false, 'DRIVER', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());

MERGE INTO drivers (user_id, active_driver, last_state_change_at) KEY (user_id) VALUES
((SELECT id FROM users WHERE email = 'jelena.milosevic@example.com'), false, CURRENT_TIMESTAMP());

-- Insert Luxury Vehicle for Driver Jelena
MERGE INTO vehicles (driver_id, license_plate, vehicle_type_id, num_seats, baby_friendly, pet_friendly, current_lat, current_lng) KEY (license_plate) VALUES
(
  (SELECT id FROM users WHERE email = 'jelena.milosevic@example.com'),
  'BG-123-CD',
  (SELECT id FROM vehicle_types WHERE name = 'LUXURY'),
  4,
  false,
  true,
  44.7866,
  20.4489
);

-- Insert Driver with VAN (baby and pet friendly) (Password: Password123)
MERGE INTO users (dtype, name, surname, email, password_hash, address, phone, profile_picture_url, blocked, role, created_at, updated_at) KEY (email) VALUES
('Driver', 'Nikola', 'Đorđević', 'nikola.djordjevic@example.com', '008c70392e3abfbd0fa47bbc2ed96aa99bd49e159727fcba0f2e6abeb3a9d601', 'Cara Dušana 15, Niš', '+381652223333', null, false, 'DRIVER', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());

MERGE INTO drivers (user_id, active_driver, last_state_change_at) KEY (user_id) VALUES
((SELECT id FROM users WHERE email = 'nikola.djordjevic@example.com'), true, CURRENT_TIMESTAMP());

-- Insert VAN Vehicle
MERGE INTO vehicles (driver_id, license_plate, vehicle_type_id, num_seats, baby_friendly, pet_friendly, current_lat, current_lng) KEY (license_plate) VALUES
(
  (SELECT id FROM users WHERE email = 'nikola.djordjevic@example.com'),
  'NI-456-EF',
  (SELECT id FROM vehicle_types WHERE name = 'VAN'),
  7,
  true,
  true,
  43.3209,
  21.8954
);

-- Insert another Passenger (Password: Password123)
MERGE INTO users (dtype, name, surname, email, password_hash, address, phone, profile_picture_url, blocked, role, created_at, updated_at) KEY (email) VALUES
('Passenger', 'Milica', 'Stojanović', 'milica.stojanovic@example.com', '008c70392e3abfbd0fa47bbc2ed96aa99bd49e159727fcba0f2e6abeb3a9d601', 'Kraljevića Marka 5, Kragujevac', '+381663334444', null, false, 'PASSENGER', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());

MERGE INTO passengers (user_id) KEY (user_id) VALUES ((SELECT id FROM users WHERE email = 'milica.stojanovic@example.com'));

COMMIT;
